#!/bin/bash
echo "Helping..."
echo ""
echo ""

echo "📚 CCPM - Project Management Skill"
echo "============================================="
echo ""
echo "🎯 Quick Start Workflow"
echo "  1. \"I want to build <name>\""
echo "  2. \"parse the <name> PRD\""
echo "  3. \"break down the <name> epic\""
echo "  4. \"sync the <name> epic to GitHub\""
echo "  5. \"start working on issue <N>\""
echo ""
echo "📄 PRD Commands"
echo "  \"I want to build <name>\"   - Launch brainstorming for a new requirement"
echo "  \"parse the <name> PRD\"    - Convert a PRD to an implementation epic"
echo "  \"list PRDs\"               - List all PRDs"
echo "  \"edit the <name> PRD\"     - Edit an existing PRD"
echo "  \"PRD status\"              - Show PRD implementation status"
echo ""
echo "📚 Epic Commands"
echo "  \"break down the <name> epic\"      - Break an epic into task files"
echo "  \"sync the <name> epic to GitHub\"  - Push epic and tasks to GitHub"
echo "  \"list epics\"                      - List all epics"
echo "  \"show the <name> epic\"            - Display an epic and its tasks"
echo "  \"status of the <name> epic\"       - Show epic progress"
echo "  \"close the <name> epic\"           - Mark an epic as complete"
echo "  \"edit the <name> epic\"            - Edit epic details"
echo "  \"start work on the <name> epic\"   - Launch parallel execution"
echo ""
echo "📝 Issue Commands"
echo "  \"show issue <N>\"                 - Display issue and sub-issues"
echo "  \"issue <N> status\"               - Check issue status"
echo "  \"start working on issue <N>\"     - Begin work with parallel analysis"
echo "  \"sync issue <N>\"                 - Push updates to GitHub"
echo "  \"close issue <N>\"                - Mark issue as complete"
echo "  \"reopen issue <N>\"               - Reopen a closed issue"
echo "  \"analyze issue <N>\"              - Analyze for parallel work streams"
echo ""
echo "🔄 Workflow Commands"
echo "  \"what's next\"                    - Show next priority tasks"
echo "  \"what's our status\"              - Overall project dashboard"
echo "  \"standup\"                        - Daily standup report"
echo "  \"what's blocked\"                 - Show blocked tasks"
echo "  \"what's in progress\"             - List work in progress"
echo ""
echo "🔗 Sync Commands"
echo "  \"sync the epic to GitHub\"        - Push local state to GitHub"
echo ""
echo "🔧 Maintenance Commands"
echo "  \"validate project state\"         - Check system integrity"
echo "  \"search for <query>\"             - Search across all content"
echo ""
echo "⚙️  Setup Commands"
echo "  \"create project context\"         - Build durable context files"
echo "  \"figure out the test setup\"      - Detect and save testing config"
echo "  \"run tests for <target>\"         - Run tests with log capture"
echo ""
echo "💡 Tips"
echo "  • Ask CCPM what's next to find available work"
echo "  • Ask CCPM for status for a quick overview"
echo "  • Epic workflow: plan → parse → break down → sync"
echo "  • View README.md for complete documentation"

exit 0
